# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TVESAS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TVESAS
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SVProgressHUD'
  pod 'IQKeyboardManagerSwift', '~> 5.0.2'
  pod 'SDWebImage'
  target 'TVESASTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TVESASUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
